launch=pipe
pipe-command=/usr/local/bin/cf-pipe-backend.py
pipe-timeout=5000
pipe-abi-version=1

local-port=53
local-address=0.0.0.0,::

webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=0.0.0.0/0,::/0
api=yes
api-key=changeme

zone-cache-refresh-interval=0

# Only authoritative for our domain
query-logging=no
log-dns-queries=no
